name: Build & Release
on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build-n-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22'

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date --iso-8601=seconds) >> ${GITHUB_ENV}
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: wangyoucao577/go-release-action@v1
        with:
          pre_command: export CGO_ENABLED=0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: -X "main.buildTime=${{ env.BUILD_TIME }}" -X "main.commitHash=${{ github.sha }}" -X "main.version=${{ env.APP_VERSION }}"
